"""empty message

Revision ID: 183341731bc1
Revises: 40bc44aaf9dd
Create Date: 2017-01-02 18:33:24.847354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183341731bc1'
down_revision = '40bc44aaf9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_uid', sa.Integer(), nullable=True),
    sa.Column('stop_custom_name', sa.Unicode(), nullable=True),
    sa.Column('stop_id', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.Unicode(), nullable=True),
    sa.Column('last_location', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_locations')
    op.drop_table('bus_stops')
    # ### end Alembic commands ###
