"""empty message

Revision ID: 201626a58dfd
Revises: 
Create Date: 2016-12-28 10:33:44.274968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201626a58dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
